"""BananaChat database package: flat re-export of all public symbols."""

from ._connection import (  # noqa: F401
    get_db,
    get_db_context,
    get_database_health,
    write_serialized,
    retry_on_busy,
    integrity_check,
    create_consistent_backup,
    SYSTEM_USER_ID,
)

from ._schema import init_db  # noqa: F401

from ._settings import (  # noqa: F401
    get_site_settings,
    update_site_settings,
)

from ._users import (  # noqa: F401
    get_user_by_id,
    get_user_by_username,
    create_user,
    create_signup_user,
    complete_initial_setup,
    update_last_login,
    change_password,
    delete_user,
    list_users,
    suspend_user,
    unsuspend_user,
    set_user_role,
    count_users,
    count_admins,
    is_suspension_active,
    check_suspension_expired,
    record_login_attempt,
    check_login_rate_limit,
    clear_login_attempts,
    check_rate_limit,
    collect_user_gdpr_data,
    get_user_accessibility,
    save_user_accessibility,
    _A11Y_DEFAULTS,
    _clean_a11y_pref,
)

from ._invites import (  # noqa: F401
    generate_invite_code,
    validate_invite_code,
    use_invite_code,
    delete_invite_code,
    list_invite_codes,
    list_expired_codes,
    get_invite_code_usage,
)

from ._models import (  # noqa: F401
    list_models,
    get_model_by_id,
    get_model_by_ollama_name,
    upsert_model,
    sync_ollama_models,
    sync_comfyui_models,
    set_model_rollout,
    update_model,
    delete_model,
    build_model_options,
    get_model_system_prompt,
    list_categories,
    create_category,
    update_category,
    delete_category,
    assign_model_category,
    remove_model_category,
    get_model_categories,
    list_models_with_categories,
    reorder_models,
    reorder_categories,
)

from ._access import (  # noqa: F401
    ACCESS_SCOPES,
    ACCESS_MODES,
    ACCESS_LIST_TYPES,
    get_access_policy,
    set_access_policy,
    list_access_policies,
    add_access_membership,
    remove_access_membership,
    list_access_memberships,
    is_user_allowed_by_policy,
    create_access_request,
    get_access_request,
    get_pending_access_request,
    list_access_requests,
    resolve_access_request,
)

from ._personalities import (  # noqa: F401
    MAX_PERSONALITIES_PER_USER,
    MAX_PERSONALITY_NAME,
    MAX_PERSONALITY_INSTRUCTIONS,
    create_personality,
    get_personality,
    list_user_personalities,
    list_all_personalities,
    update_personality,
    set_personality_moderation,
    delete_personality,
    personality_is_active,
)

from ._tokens import (  # noqa: F401
    list_tokens,
    count_active_tokens,
    create_token,
    rotate_token,
    rename_token,
    revoke_token,
    get_token_by_hash,
    touch_token,
    hash_token,
    MAX_TOKENS_PER_USER,
)

from ._credits import (  # noqa: F401
    tokens_to_credits,
    get_user_quota,
    set_user_quota,
    get_today_usage,
    deduct_credits,
    reserve_image_credits,
    touch_image_credit_reservation,
    refund_image_credit_reservation,
    finalize_image_credit_reservation,
    InsufficientImageCreditsError,
    ImageCreditReservationError,
    check_credits_available,
    check_chat_credits_available,
    get_usage_history,
    submit_quota_request,
    create_quota_request,
    get_pending_quota_request,
    list_quota_requests,
    list_user_quota_requests,
    resolve_quota_request,
    TOKENS_PER_CREDIT,
    DEFAULT_DAILY_CREDITS,
    DEFAULT_DAILY_SLOW_CREDITS,
)

from ._chat import (  # noqa: F401
    create_session,
    get_session,
    get_session_by_share_token,
    update_session_title,
    touch_session,
    create_share_token,
    revoke_share_token,
    delete_session,
    close_incognito_session,
    delete_all_user_sessions,
    list_sessions,
    list_user_sessions_for_export,
    get_latest_empty_session,
    list_messages,
    list_message_page,
    iter_messages,
    add_message,
    add_message_with_attachments,
    set_session_personality,
    get_message,
    list_session_attachments,
    list_session_attachment_metadata,
    get_session_attachment_bytes,
    session_has_image_attachments,
    get_attachment,
    list_incognito_audit,
    delete_incognito_entry,
    delete_incognito_session,
    purge_expired_incognito_sessions,
    list_all_sessions_admin,
    count_all_sessions_admin,
    count_incognito_audit,
    admin_hard_delete_session,
    search_sessions,
)

from ._metrics import (  # noqa: F401
    record_compute_snapshot,
    record_request_metric,
    get_compute_history,
    get_request_stats,
    get_latest_snapshot,
    purge_old_metrics,
)

from ._pull import (  # noqa: F401
    enqueue_pull_job,
    list_pull_jobs,
    get_pull_job,
    claim_next_pull_job,
    update_pull_job_progress,
    set_pull_job_remote_id,
    is_pull_job_cancelled,
    finish_pull_job,
    cancel_pull_job,
    reset_stuck_pulls,
    delete_pull_job,
    clear_pull_history,
)

from ._runtime import (  # noqa: F401
    register_active_stream,
    touch_active_stream,
    active_stream_should_stop,
    request_stop_stream,
    deregister_active_stream,
    is_active_stream,
    update_stream_partial_content,
    get_stream_partial_content,
)

from ._music import (  # noqa: F401
    get_music_settings,
    update_music_settings,
    is_user_music_opted_in,
    set_user_music_opt_in,
    is_user_music_forced,
    opt_in_all_users,
    opt_out_all_users,
    remove_program,
    count_music_opted_in,
    get_effective_quota_multiplier,
    get_effective_quota_bonus,
    list_music_tracks,
    get_music_track,
    add_music_track,
    rename_music_track,
    delete_music_track,
    reorder_music_tracks,
)

from ._workers import (  # noqa: F401
    create_worker,
    get_worker_by_token,
    get_worker_by_id,
    update_worker_heartbeat,
    set_worker_disabled,
    delete_worker,
    list_workers,
    get_available_worker,
    WORKER_HEARTBEAT_LEASE,
)

from ._worker_jobs import (  # noqa: F401
    create_worker_job,
    claim_next_worker_job,
    get_worker_job,
    finish_worker_job,
    request_stop_worker_job,
    should_stop_worker_job,
    purge_old_worker_jobs,
    add_worker_chunk,
    get_worker_chunks_after,
    purge_worker_job_chunks,
)
